### PR TITLE
cant wait to become a professional lodasher

### PR DESCRIPTION
**Pull request by jrutishauser**

### CODE REVIEW

**Comment by jrutishauser** [comment]
https://github.com/TheIronYard--Orlando/FEE--2015--SPRING/issues/175

**Comment by jrutishauser** [comment]
{ total: 30, PushEvent: { total: 13 } }
30

**Comment by jrutishauser** [comment]
new outputs { total: 30,
  PushEvent: { total: 13 },
  PullRequestEvent: { total: 3 },
  IssueCommentEvent: { total: 11 },
  CreateEvent: { total: 1 },
  DeleteEvent: { total: 1 },
  IssuesEvent: { total: 1 } }

**Comment by jgarcia99** [comment]
:+1:

**Comment by sak55** [comment]
thumb, thumb thumb thumb, thummmmmmmmb :+1:

**Comment by sak55** [comment]
### comment2

 total: 30, PushEvent: { total: 9 } }
[]

  ✓ should have events 
  ✓ should have answer 
  ✓ should return the length of events when calling answer 
  ✓ should have "pushEvent" and has a total count of push 

  4 passing (6ms)

**Comment by jrutishauser** [comment]
^ LOLOLOLOL @sak55

**Pull request merged**
