### PR TITLE
Feature/05  more layout

### PR DESCRIPTION
**Pull request by jrutishauser**

### CODE REVIEW

**Comment by jrutishauser** [comment]
https://github.com/TheIronYard--Orlando/FEE--2015--SPRING/issues/81

**Comment by jrutishauser** [comment]
http://jrutishauser.github.io/TIY-Assignments/

**Comment by jrutishauser** [comment]
https://github.com/jrutishauser/TIY-Assignments/issues/7

**Comment by johnalxndr** [comment]
:+1: BEA-UTIFUL

**Pull request merged**
