### PR TITLE
standard assignment branch pull request

### PR DESCRIPTION
**Pull request by jrutishauser**

### CODE REVIEW

**Comment by jrutishauser** [comment]
https://github.com/TheIronYard--Orlando/FEE--2015--SPRING/issues/111

**Comment by jrutishauser** [comment]
http://jrutishauser.github.io/

**Comment by jrutishauser** [comment]
:-1: http://htmlpreview.github.io/?https://github.com/jrutishauser/TIY-Assignments/blob/08--surf%2Bpaddle%2Brwd/pub/index.html

**Comment by jrutishauser** [comment]
https://github.com/jrutishauser/TIY-Assignments/issues/12

**Comment by jrutishauser** [comment]
https://github.com/jrutishauser/TIY-Assignments/issues/11

**Comment by johnalxndr** [comment]
:+1: !!

**Comment by mfees** [comment]
:+1: 
you go girl

**Comment by mfees** [comment]
boy\* :D

**Comment by jgarcia99** [comment]
:+1:

**Comment by jrutishauser** [comment]
[david check this out, what do you think about this strat?](https://www.youtube.com/watch?v=dQw4w9WgXcQ)

**Pull request merged**
