### PR TITLE
welcome to the coding dojo

### PR DESCRIPTION
**Pull request by jrutishauser**

### CODE REVIEW

**Comment by jgarcia99** [comment]
:+1:

**Comment by jrutishauser** [comment]
https://github.com/TheIronYard--Orlando/FEE--2015--SPRING/issues/146

**Comment by jrutishauser** [comment]
https://github.com/jrutishauser/javascript-koans/pull/1

**Comment by jrutishauser** [comment]
http://jrutishauser.github.io/jekyll/update/2015/01/25/third-week.html

**Pull request merged**
