### PR TITLE
 added the skitches

### PR DESCRIPTION
**Pull request by jrutishauser**

### CODE REVIEW

**Comment by jrutishauser** [comment]
https://github.com/TheIronYard--Orlando/FEE--2015--SPRING/issues/92

**Comment by jrutishauser** [comment]
https://github.com/jrutishauser/TIY-Assignments/blob/feature/06--more-responsive/pub/index.html

**Comment by jrutishauser** [comment]
https://github.com/jrutishauser/TIY-Assignments/issues/9

**Comment by mfees** [comment]
:+1: 
Woot woot!

**Comment by eklemen** [comment]
:+1:  awesome!

**Comment by jrutishauser** [comment]
http://jrutishauser.github.io/TIY-Assignments/pub/index.html

**Pull request merged**
